Complete the add, sub, and mul operators to complete unit testing and…
PNP-team/PNP pull request #7
Opened 2023-12-13 07:12 UTC by wynneyin

2023-12-13 08:36 UTC, zlyber commented on torch/nn/functional.py
It is recommended to remove all codes and files related to ```ntt``` module from your branch.

2023-12-13 08:38 UTC, zlyber commented on torch/testing/_internal/zkp_test_lists.py
> +                # print(mont1,mont2)
still redundant codes.

2023-12-13 08:38 UTC, zlyber commented on 2.py
> +# 构建模型
no Chinese please...

2023-12-13 08:42 UTC, wynneyin commented
Sorry for forgetting this file, I will modify it&nbsp;


尹文浩
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhiyuan ***@***.***&gt;; 
发送时间: 2023年12月13日(星期三) 下午4:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PNP-team/PNP] Complete the add, sub, and mul operators to complete unit testing and… (PR #7)





 
@zlyber commented on this pull request.
 
 
In 2.py:
 &gt; +        return grad_input + +class to_mod(torch.autograd.Function): +    @staticmethod +    def forward(ctx, in_1): +        ctx.save_for_backward(in_1) +        output = F.to_mod(in_1) +        return output + +    @staticmethod +    def backward(ctx, grad_output): +        input, = ctx.saved_tensors +        grad_input =grad_output +        return grad_input    + +# 构建模型  
no Chinese please...
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2023-12-13 08:43 UTC, zlyber requested changes
1. There is still redundant codes and comments, check all your commits more carefully.
2. No Chinese.
3. Only two curves are tested now, should we support other curves at this stage? @jizhuoran

2023-12-15 09:36 UTC, wynneyin commented
1. Native_ Function_ Generation.py was modified because I added an equal_ The mod function, the return value of this function is of type bool, not of type tensor.
2. Unittest_ Mod. py is the test file, and I will move it to the test folder

&nbsp;


尹文浩
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhuoran ***@***.***&gt;; 
发送时间: 2023年12月15日(星期五) 下午5:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PNP-team/PNP] Complete the add, sub, and mul operators to complete unit testing and… (PR #7)





 
Some quick comments.
 
First, test file like the 1.py, 2.py files should be removed.
 
Second, ntt family function should be removed from functional.py
 
Third, pay attention to the space/new line/{, please follow the original format. You can check the modification in this tab.
 Screenshot.2023-12-15.at.17.22.13.png (view on web)
 
Forth, the function name should follow the same format. For add, it is add_cpu (I think it should be add_mod_cpu), while for sub_mod_, it becomes subtraction_cpu_. Meanwhile, why there is comments like ##div in the yarm file.
 
Fifth, why torchgen/native_function_generation.py is changed?
 
Sixth, what's the function of unittest_mod.py?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2023-12-20 14:24 UTC, closed without merging